Added support for django's builtin bulk_update method if present
Tesorio/django-anon pull request #56
Opened 2020-10-02 18:10 UTC by deeaarbee

Fix for using django's builtin bulk_update method if available
[Link](https://github.com/Tesorio/django-anon/issues/48) for the issue

## Todos

- [x] Tests
- [x] Documentation
- [ ] Changelog

2020-10-05 19:49 UTC, caioariede requested changes
Thank you @deeaarbee it looks really good! Just some minor suggestions :)

2020-10-05 19:49 UTC, caioariede commented on anon/compat.py
> +        django_bulk_update's `bulk_update` will be used
📖 Could you please add parameters to the docstring?

[https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html)

For example:

```python
"""
This is what this method does...

:param arg1: first argument
:type arg1: int
:param arg2: second argument
:type arg2: str
:return: A list of items
:rtype: list
"""
```

2020-10-05 19:49 UTC, caioariede commented on anon/compat.py
> +        inbuilt `.bulk_update()` method if present, else
📖 This is an invalid reStructuredText markup. Inline literals use double backticks:

[https://docutils.sourceforge.io/docs/user/rst/quickref.html](https://docutils.sourceforge.io/docs/user/rst/quickref.html)

2020-10-05 19:49 UTC, caioariede commented on anon/compat.py
> +        ext_bulk_update(objects, bulk_update_kwargs)
🎨 It's easier to ask for forgiveness than permission (EAFP):

[https://docs.python.org/3.4/glossary.html](https://docs.python.org/3.4/glossary.html)

```suggestion
    try:
        manager.bulk_update(objects, **bulk_update_kwargs)
    except AttributeError:
        ext_bulk_update(objects, bulk_update_kwargs)
```

2020-10-05 19:49 UTC, caioariede commented on anon/compat.py
> +def bulk_update(objects, manager, **bulk_update_kwargs):
I think we need to add a unit test to this function

2020-10-11 17:51 UTC, deeaarbee commented on anon/compat.py
> +        django_bulk_update's `bulk_update` will be used
I have added the parameters to the docstring. Please verify the format.

2020-10-11 17:51 UTC, deeaarbee commented on anon/compat.py
> +        inbuilt `.bulk_update()` method if present, else
Thanks for the reference. I have updated the docstring.

2020-10-11 17:52 UTC, deeaarbee commented on anon/compat.py
> +def bulk_update(objects, manager, **bulk_update_kwargs):
Added unit test for the method. Please confirm if the test case makes sense.

2020-10-11 17:57 UTC, deeaarbee commented on anon/compat.py
> +        ext_bulk_update(objects, bulk_update_kwargs)
Updated the code with your suggestion.

2020-10-13 12:53 UTC, caioariede commented
That's awesome, thanks @deeaarbee :) The coverage is failing for other reasons as far as I can tell.

Can you please just add a new bullet under the **master** section in the `CHANGELOG`?

https://github.com/Tesorio/django-anon/blob/master/CHANGELOG.rst#master

Thanks again!

2020-10-14 11:10 UTC, merged

2020-10-14 11:11 UTC, caioariede commented
@deeaarbee thank you for your contribution 🙏